name: Continus Integration

on: push

env: 
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 18.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 18.x
      - name: Install depenencies
        run: npm ci
      - name: Test
        run: npm run lint